### ISSUE TITLE
Error during init start

### ISSUE THREAD

**Issue by LubomirIgonda1** [jsreport/jsreport-extension-starter-kit#2]
Hi I try to run example by documentation but I still got this error 
![obrázok](https://user-images.githubusercontent.com/9303146/140068653-a99be890-3612-420f-91e5-981a6e80d8b0.png)

ENV:
WIN 10
node: 16.13.0

step to reproduce:
1. download this package
2. npm install
3. npm start => get error

Do I something wrong ?

**Comment by bjrmatos** [comment]
ups, sorry for this, i can reproduce the issue, will check and post updates here. thanks for the bug report

**Comment by bjrmatos** [comment]
so i fixed this, be sure to clone the repository again and npm install and npm start again, you should now be able to load the studio normally.

however please note that the error will still be shown on the first npm start during the install of jsreport-studio deps, on the first run we install jsreport, and jsreport-studio deps, which trigger a build of jsreport-studio that right now is failing because it needs that we publish some other changes to npm which we plan to release some weeks later, however that error won't affect the npm start to continue to run and build as expected. please verify this. 

so as a TL;DR first npm start will install jsreport, install jsreport-studio deps, will trigger jsreport-studio build, which will result in the error you reported, from there the process will continue, jsreport will be started and finally the custom extension at the root will be build with no error.
